class appdata {
  static List<Map<String, Object?>> orderItems = [
    {
      'Item': 'Tricycle',
      'Quantity': 1,
      'Price': 175,
      'Location': ['Alexandria', 'sidi beshr', 'El-Agamy'],
      'Time': '8 march, 2.30',
      'Additional Notes': 'Ridden by Mohamed',
    },
    {
      'Item': 'Rob3 Naa1',
      'Quantity': 1,
      'Price': 300,
      'Location': ['Alexandria', 'EL-Salam2', 'Omar El-Mokhtar'],
      'Additional Notes': 'Transported, not operational',
    },
    {
      'Item': 'Wooden Cabinet',
      'Quantity': 1,
      'Size': '160 * 250',
      'Price': 300,
      'Location': null,
      'Additional Notes': 'Uploaded photos by Menna',
    },
    {
      'Item': 'Tricycle',
      'Quantity': 1,
      'Price': 175,
      'Location': ['Alexandria', 'sidi beshr', 'El-Agamy'],
      'Time': '8 march, 2.30',
      'Additional Notes': 'Ridden by Mohamed',
    },
    {
      'Item': 'Rob3 Naa1',
      'Quantity': 1,
      'Price': 300,
      'Location': ['Alexandria', 'EL-Salam2', 'Omar El-Mokhtar'],
      'Additional Notes': 'Transported, not operational',
    },
    {
      'Item': 'Wooden Cabinet',
      'Quantity': 1,
      'Price': 300,
      'Size': '160 * 250',
      'Location': null,
      'Additional Notes': 'Uploaded photos by Menna',
    },
    {
      'Item': 'Tricycle',
      'Quantity': 1,
      'Price': 175,
      'Location': ['Alexandria', 'sidi beshr', 'El-Agamy'],
      'Time': '8 march, 2.30',
      'Additional Notes': 'Ridden by Mohamed',
    },
    {
      'Item': 'Rob3 Naa1',
      'Quantity': 1,
      'Price': 300,
      'Location': ['Alexandria', 'EL-Salam2', 'Omar El-Mokhtar'],
      'Additional Notes': 'Transported, not operational',
    },
    {
      'Item': 'Wooden Cabinet',
      'Quantity': 1,
      'Price': 300,
      'Size': '160 * 250',
      'Location': null,
      'Additional Notes': 'Uploaded photos by Menna',
    },
    {
      'Item': 'Tricycle',
      'Quantity': 1,
      'Price': 175,
      'Location': ['Alexandria', 'sidi beshr', 'El-Agamy'],
      'Time': '8 march, 2.30',
      'Additional Notes': 'Ridden by Mohamed',
    },
    {
      'Item': 'Rob3 Naa1',
      'Quantity': 1,
      'Price': 300,
      'Location': ['Alexandria', 'EL-Salam2', 'Omar El-Mokhtar'],
      'Additional Notes': 'Transported, not operational',
    },
    {
      'Item': 'Rob3 Naa1',
      'Quantity': 1,
      'Price': 300,
      'Location': ['Alexandria', 'EL-Salam2', 'Omar El-Mokhtar'],
      'Additional Notes': 'Transported, not operational',
    },
  ];
}
